---
- hosts: all
  gather_facts: true
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include custom configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: Ensure apt cache is updated.
      apt:
        update_cache: true
        cache_valid_time: 3600

  tasks:
    - import_tasks: tasks/base-system.yml
      tags: ['base-system']
      when: configure_system

    - import_tasks: tasks/update-packages.yml
      tags: ['base-system']
      when: update_packages


- hosts: master
  become: true
  vars_files:
    - default.config.yml
  roles:
    - k3s-common
    - k3s-master


- hosts: worker
  become: true
  vars_files:
    - default.config.yml
  roles:
    - k3s-common
    - k3s-worker
